"""Complaint-type playbooks: ask only what that problem needs."""

from __future__ import annotations

PLAYBOOKS: list[dict] = [
    {
        "id": "water",
        "title": "Water is not coming",
        "title_hi": "पानी नहीं आ रहा",
        "blurb": "Dry tap, dirty supply, or a broken pipeline.",
        "blurb_hi": "सूखा नल, गंदा पानी, या टूटी पाइपलाइन।",
        "keywords": ["water", "pipeline", "paani", "jal", "tap", "tanker", "borewell", "पानी", "पाइप", "नल", "टैंकर"],
        "ministry": "Ministry of Housing and Urban Affairs",
        "category": "Water supply / civic amenities",
        "needs_photo": True,
        "photo_prompt": "Take a photo of the dry tap, tanker, or the broken pipe. That is the proof.",
        "photo_prompt_hi": "सूखे नल, टैंकर या टूटी पाइप की फोटो लें। यही प्रमाण है।",
        "doc_prompt": "Optional: a water bill or a notice from the jal board. Never Aadhaar or PAN.",
        "doc_prompt_hi": "वैकल्पिक: जल बिल या जल बोर्ड का नोटिस। आधार या पैन कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is wrong with the water?",
                "label_hi": "पानी में क्या समस्या है?",
                "type": "choice",
                "options": ["No supply", "Dirty / smelly water", "Leak or burst pipe", "Tanker did not come"],
                "options_hi": ["आपूर्ति नहीं", "गंदा / बदबूदार पानी", "रिसाव या फटी पाइप", "टैंकर नहीं आया"],
            },
            {
                "id": "days",
                "label": "How long has this been going on?",
                "label_hi": "यह कब से हो रहा है?",
                "type": "choice",
                "options": ["Today", "2–7 days", "More than a week", "More than a month"],
                "options_hi": ["आज", "2–7 दिन", "एक सप्ताह से अधिक", "एक महीने से अधिक"],
            },
            {
                "id": "spread",
                "label": "Who is affected?",
                "label_hi": "किस पर असर है?",
                "type": "choice",
                "options": ["Only my house", "This gali / street", "The whole village or ward"],
                "options_hi": ["केवल मेरा घर", "यह गली / सड़क", "पूरा गाँव या वार्ड"],
            },
            {
                "id": "source",
                "label": "Do you know the source?",
                "label_hi": "स्रोत पता है?",
                "type": "choice",
                "options": ["Municipal tap", "Handpump / borewell", "Tanker", "Unknown"],
                "options_hi": ["नगरपालिका नल", "हैंडपंप / बोरवेल", "टैंकर", "अज्ञात"],
            },
        ],
    },
    {
        "id": "road",
        "title": "Road is blocked or broken",
        "title_hi": "सड़क बंद या टूटी है",
        "blurb": "Jam, potholes, a fallen tree, or a cut that no one filled.",
        "blurb_hi": "जाम, गड्ढे, गिरा पेड़, या खोदी गई सड़क जिसे भरा नहीं गया।",
        "keywords": ["road", "sarak", "pothole", "jam", "blocked", "highway", "culvert", "gaddha", "सड़क", "सडक", "गड्ढा", "जाम"],
        "ministry": "Ministry of Road Transport and Highways",
        "category": "Road / transport",
        "needs_photo": True,
        "photo_prompt": "Photograph the blockage or the broken stretch so the desk can see it.",
        "photo_prompt_hi": "रुकावट या टूटे हिस्से की फोटो लें ताकि डेस्क देख सके।",
        "doc_prompt": "Optional: a previous complaint number. Never Aadhaar or PAN.",
        "doc_prompt_hi": "वैकल्पिक: पिछली शिकायत संख्या। आधार या पैन कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is wrong with the road?",
                "label_hi": "सड़क में क्या समस्या है?",
                "type": "choice",
                "options": ["Blocked right now", "Deep potholes", "Broken culvert / bridge", "No work after digging"],
                "options_hi": ["अभी बंद है", "गहरे गड्ढे", "टूटा पुलिया / पुल", "खोदने के बाद काम नहीं"],
            },
            {
                "id": "days",
                "label": "Since when?",
                "label_hi": "कब से?",
                "type": "choice",
                "options": ["Today", "A few days", "Weeks", "Months"],
                "options_hi": ["आज", "कुछ दिन", "सप्ताह", "महीने"],
            },
            {
                "id": "traffic",
                "label": "What cannot pass?",
                "label_hi": "क्या नहीं निकल पा रहा?",
                "type": "choice",
                "options": ["Two-wheelers only struggling", "Cars and jeeps", "Buses and trucks", "Ambulance / school also stuck"],
                "options_hi": ["केवल दोपहिया मुश्किल से", "कार और जीप", "बस और ट्रक", "एम्बुलेंस / स्कूल भी फँसे"],
            },
        ],
    },
    {
        "id": "waste",
        "title": "Garbage, drain, or river waste",
        "title_hi": "कचरा, नाला या नदी का कचरा",
        "blurb": "Dump, nala, or waste near homes — the questions the rural field desk used.",
        "blurb_hi": "घरों के पास ढेर, नाला या कचरा।",
        "keywords": ["garbage", "kooda", "drain", "nala", "sewage", "waste", "nadi", "dump", "alag", "कचरा", "कूड़ा", "नाला", "गंदगी"],
        "ministry": "Ministry of Housing and Urban Affairs",
        "category": "Sanitation / waste",
        "needs_photo": True,
        "photo_prompt": "Photograph the dump, nala, or river edge. Stand far enough to show how close homes are.",
        "photo_prompt_hi": "ढेर, नाला या नदी किनारे की फोटो लें। घर कितने पास हैं यह दिखे।",
        "doc_prompt": "Optional: a notice from the panchayat. Never Aadhaar or PAN.",
        "doc_prompt_hi": "वैकल्पिक: पंचायत का नोटिस। आधार या पैन कभी नहीं।",
        "questions": [
            {
                "id": "type",
                "label": "What kind of waste is it?",
                "label_hi": "यह किस तरह का कचरा है?",
                "type": "choice",
                "options": ["Household dump", "Drain / sewage", "Industrial waste", "River weed or floating waste"],
                "options_hi": ["घरेलू ढेर", "नाला / सीवेज", "औद्योगिक कचरा", "नदी की घास या तैरता कचरा"],
            },
            {
                "id": "affect",
                "label": "How is it hurting people nearby?",
                "label_hi": "आसपास के लोगों को क्या नुकसान है?",
                "type": "choice",
                "options": ["Foul smell", "Mosquitoes", "Spreading illness", "Bad air", "Not affecting homes yet"],
                "options_hi": ["दुर्गंध", "मच्छर", "बीमारी फैल रही", "खराब हवा", "अभी घरों पर असर नहीं"],
            },
            {
                "id": "distance",
                "label": "How close is it to houses?",
                "label_hi": "घरों से कितनी दूरी है?",
                "type": "choice",
                "options": ["0–100 metres", "100–500 metres", "More than 500 metres"],
                "options_hi": ["0–100 मीटर", "100–500 मीटर", "500 मीटर से अधिक"],
            },
            {
                "id": "source",
                "label": "Is the source known?",
                "label_hi": "स्रोत पता है?",
                "type": "text",
                "hint": "Factory name, market, or write Unknown.",
                "hint_hi": "कारखाने का नाम, बाज़ार, या अज्ञात लिखें।",
            },
        ],
    },
    {
        "id": "cyber",
        "title": "Cyber fraud or online cheat",
        "title_hi": "साइबर धोखा या ऑनलाइन ठगी",
        "blurb": "UPI scam, fake call, hacked account — we capture the case, not your passwords.",
        "blurb_hi": "यूपीआई ठगी, फर्जी कॉल, हैक खाता — मामला दर्ज होता है, पासवर्ड नहीं।",
        "keywords": ["cyber", "upi fraud", "phishing", "hack", "scam", "otp fraud", "fake call", "online fraud", "धोखा", "फर्जी", "यूपीआई"],
        "ministry": "Ministry of Electronics and Information Technology",
        "category": "Cyber / digital fraud",
        "needs_photo": True,
        "photo_prompt": "Screenshot the fraud message or the payment screen. Hide any OTP or PIN before you upload.",
        "photo_prompt_hi": "ठगी संदेश या भुगतान स्क्रीन का स्क्रीनशॉट लें। अपलोड से पहले ओटीपी या पिन छिपाएँ।",
        "doc_prompt": "Optional: bank SMS of the debit. Never Aadhaar, PAN, OTP, or full card number.",
        "doc_prompt_hi": "वैकल्पिक: डेबिट का बैंक एसएमएस। आधार, पैन, ओटीपी या पूरा कार्ड नंबर कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What kind of cheat was this?",
                "label_hi": "यह किस तरह की ठगी थी?",
                "type": "choice",
                "options": ["UPI / payment fraud", "Fake call or WhatsApp", "Hacked social or email", "Job / KYC phishing"],
                "options_hi": ["यूपीआई / भुगतान ठगी", "फर्जी कॉल या व्हाट्सऐप", "हैक सोशल या ईमेल", "नौकरी / केवाईसी फिशिंग"],
            },
            {
                "id": "when",
                "label": "When did it happen?",
                "label_hi": "यह कब हुआ?",
                "type": "text",
                "hint": "Date and roughly the time.",
                "hint_hi": "तारीख और लगभग समय।",
            },
            {
                "id": "amount",
                "label": "Money lost, if any",
                "label_hi": "कितना पैसा गया, यदि गया हो",
                "type": "text",
                "hint": "Amount in rupees, or write None.",
                "hint_hi": "रुपये में राशि, या कुछ नहीं लिखें।",
            },
            {
                "id": "channel",
                "label": "How did they reach you?",
                "label_hi": "वे आप तक कैसे पहुँचे?",
                "type": "text",
                "hint": "App name or a phone number. Not your password.",
                "hint_hi": "ऐप का नाम या फोन नंबर। पासवर्ड नहीं।",
            },
            {
                "id": "reported",
                "label": "Have you already told the bank or cybercrime.gov.in?",
                "label_hi": "क्या बैंक या cybercrime.gov.in को बता चुके हैं?",
                "type": "choice",
                "options": ["Not yet", "Told the bank", "Filed on cybercrime.gov.in", "Both"],
                "options_hi": ["अभी नहीं", "बैंक को बताया", "cybercrime.gov.in पर दर्ज", "दोनों"],
            },
        ],
    },
    {
        "id": "power",
        "title": "Electricity is out",
        "title_hi": "बिजली गई हुई है",
        "blurb": "No bijli, dangerous wires, or a wrong bill.",
        "blurb_hi": "बिजली नहीं, खतरनाक तार, या गलत बिल।",
        "keywords": ["electric", "power", "bijli", "electricity", "outage", "transformer", "बिजली", "करंट"],
        "ministry": "Ministry of Power",
        "category": "Power supply",
        "needs_photo": True,
        "photo_prompt": "Photo of the dark street, the fallen wire, or the bill. Stay away from live wires.",
        "photo_prompt_hi": "अंधेरी सड़क, गिरे तार या बिल की फोटो। जीवित तारों से दूर रहें।",
        "doc_prompt": "Optional: the electricity bill. Never Aadhaar or PAN.",
        "doc_prompt_hi": "वैकल्पिक: बिजली बिल। आधार या पैन कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the power problem?",
                "label_hi": "बिजली की क्या समस्या है?",
                "type": "choice",
                "options": ["No supply", "Voltage too low / high", "Fallen or hanging wire", "Wrong bill"],
                "options_hi": ["आपूर्ति नहीं", "वोल्टेज कम / अधिक", "गिरा या लटकता तार", "गलत बिल"],
            },
            {
                "id": "days",
                "label": "Since when?",
                "label_hi": "कब से?",
                "type": "choice",
                "options": ["Hours", "1–2 days", "More than a week"],
                "options_hi": ["घंटे", "1–2 दिन", "एक सप्ताह से अधिक"],
            },
            {
                "id": "spread",
                "label": "Who is without power?",
                "label_hi": "किसके पास बिजली नहीं है?",
                "type": "choice",
                "options": ["Only my house", "This street", "The whole village"],
                "options_hi": ["केवल मेरा घर", "यह सड़क", "पूरा गाँव"],
            },
        ],
    },
    {
        "id": "pmkisan",
        "title": "PM-KISAN or farmer scheme stopped",
        "title_hi": "पीएम-किसान या किसान योजना रुकी",
        "blurb": "Instalment not received, registration rejected, or wrong bank details.",
        "blurb_hi": "किस्त नहीं आई, पंजीकरण रद्द, या गलत बैंक विवरण।",
        "keywords": ["kisan", "pm-kisan", "pmkisan", "farmer", "instalment", "fasal", "किसान", "किस्त"],
        "ministry": "Department of Agriculture & Farmers Welfare",
        "category": "Farmers welfare / PM-KISAN",
        "needs_photo": False,
        "photo_prompt": "Optional: screenshot of the PM-KISAN portal or SMS showing stopped payment.",
        "photo_prompt_hi": "वैकल्पिक: पीएम-किसान पोर्टल या रुके भुगतान का स्क्रीनशॉट।",
        "doc_prompt": "Optional: bank passbook page. Never Aadhaar, PAN number, or OTP.",
        "doc_prompt_hi": "वैकल्पिक: बैंक पासबुक का पन्ना। आधार, पैन या ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "Instalment stopped after a few payments",
                    "Never received any instalment",
                    "Registration rejected or pending",
                    "Wrong bank account linked",
                ],
                "options_hi": [
                    "कुछ किस्तों के बाद रुक गई",
                    "कोई किस्त नहीं मिली",
                    "पंजीकरण रद्द या लंबित",
                    "गलत बैंक खाता जुड़ा है",
                ],
            },
            {
                "id": "since",
                "label": "Since when have payments stopped?",
                "label_hi": "किस्त कब से रुकी है?",
                "type": "choice",
                "options": ["Last 1 instalment", "2–3 instalments", "More than 4 instalments", "Never started"],
                "options_hi": ["पिछली 1 किस्त से", "2–3 किस्तें", "4 से अधिक किस्तें", "कभी शुरू नहीं हुई"],
            },
            {
                "id": "registered",
                "label": "Is the mobile number linked to Aadhaar registered on the PM-KISAN portal?",
                "label_hi": "क्या आधार से जुड़ा मोबाइल नंबर पीएम-किसान पोर्टल पर दर्ज है?",
                "type": "choice",
                "options": ["Yes", "Not sure", "No"],
                "options_hi": ["हाँ", "पता नहीं", "नहीं"],
            },
        ],
    },
    {
        "id": "income_tax",
        "title": "Income tax refund or PAN issue",
        "title_hi": "आयकर रिफंड या पैन समस्या",
        "blurb": "Refund not received, PAN not issued, wrong demand notice.",
        "blurb_hi": "रिफंड नहीं मिला, पैन नहीं आया, गलत माँग नोटिस।",
        "keywords": ["income tax", "refund", "pan", "itr", "gst", "tax", "assessment", "demand", "पैन", "रिफंड"],
        "ministry": "Central Board of Direct Taxes",
        "category": "Income tax / GST",
        "needs_photo": False,
        "photo_prompt": "Screenshot of the e-filing portal showing the error or wrong demand.",
        "photo_prompt_hi": "ई-फाइलिंग पोर्टल का स्क्रीनशॉट जो गड़बड़ी दिखाता हो।",
        "doc_prompt": "Optional: ITR acknowledgement. Never OTP, password, or full PAN number.",
        "doc_prompt_hi": "वैकल्पिक: ITR पावती। ओटीपी, पासवर्ड या पूरा पैन नंबर कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": ["Refund not received", "Wrong demand notice", "PAN not issued / error", "Technical error on portal"],
                "options_hi": ["रिफंड नहीं मिला", "गलत माँग नोटिस", "पैन जारी नहीं / गड़बड़ी", "पोर्टल पर तकनीकी समस्या"],
            },
            {
                "id": "year",
                "label": "Which assessment year?",
                "label_hi": "कौन सा मूल्यांकन वर्ष?",
                "type": "text",
                "hint": "e.g. AY 2024-25",
                "hint_hi": "उदा. AY 2024-25",
            },
            {
                "id": "amount",
                "label": "Refund or demand amount (if known)",
                "label_hi": "रिफंड या माँग राशि (यदि पता हो)",
                "type": "text",
                "hint": "Amount in rupees, or write Unknown.",
                "hint_hi": "रुपये में राशि, या अज्ञात लिखें।",
            },
        ],
    },
    {
        "id": "banking",
        "title": "Bank, PF withdrawal, or pension delay",
        "title_hi": "बैंक, पीएफ निकासी या पेंशन देरी",
        "blurb": "PF not settled, pension stopped, banking fraud, or account access problem.",
        "blurb_hi": "पीएफ नहीं मिला, पेंशन रुकी, बैंकिंग धोखा, या खाता बंद।",
        "keywords": ["bank", "pf", "epfo", "pension", "ppo", "retirement", "epf", "savings", "account", "atm", "बैंक", "पेंशन", "पीएफ"],
        "ministry": "Department of Financial Services",
        "category": "Banking / insurance",
        "needs_photo": False,
        "photo_prompt": "Optional: passbook page, bank statement, or pension slip.",
        "photo_prompt_hi": "वैकल्पिक: पासबुक, बैंक स्टेटमेंट, या पेंशन पर्ची।",
        "doc_prompt": "Optional: passbook or bank statement. Never OTP, PIN, or full account number.",
        "doc_prompt_hi": "वैकल्पिक: पासबुक या बैंक स्टेटमेंट। ओटीपी, पिन या पूरा खाता नंबर कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "PF withdrawal pending",
                    "Pension stopped or delayed",
                    "Unauthorised debit / fraud",
                    "Account blocked or KYC problem",
                    "Bank staff harassment",
                ],
                "options_hi": [
                    "पीएफ निकासी लंबित",
                    "पेंशन रुकी या देरी",
                    "अनधिकृत डेबिट / धोखा",
                    "खाता बंद या केवाईसी समस्या",
                    "बैंक कर्मचारी का दुर्व्यवहार",
                ],
            },
            {
                "id": "since",
                "label": "How long has this been pending?",
                "label_hi": "यह कब से लंबित है?",
                "type": "choice",
                "options": ["Less than 1 month", "1–3 months", "3–6 months", "More than 6 months"],
                "options_hi": ["1 महीने से कम", "1–3 महीने", "3–6 महीने", "6 महीने से अधिक"],
            },
            {
                "id": "amount",
                "label": "Approximate amount involved",
                "label_hi": "अनुमानित राशि",
                "type": "text",
                "hint": "In rupees, or write Unknown.",
                "hint_hi": "रुपये में, या अज्ञात लिखें।",
            },
        ],
    },
    {
        "id": "telecom",
        "title": "Mobile, broadband, or SIM problem",
        "title_hi": "मोबाइल, ब्रॉडबैंड या सिम समस्या",
        "blurb": "No signal, can't port number, broadband down, or wrong bill.",
        "blurb_hi": "नेटवर्क नहीं, नंबर पोर्ट नहीं हो रहा, ब्रॉडबैंड बंद, या गलत बिल।",
        "keywords": ["mobile", "broadband", "sim", "telecom", "jio", "airtel", "bsnl", "vi", "port", "signal", "network", "मोबाइल", "नेटवर्क", "सिम"],
        "ministry": "Department of Telecommunications",
        "category": "Telecom services",
        "needs_photo": False,
        "photo_prompt": "Optional: screenshot of the error or the wrong bill.",
        "photo_prompt_hi": "वैकल्पिक: गड़बड़ी या गलत बिल का स्क्रीनशॉट।",
        "doc_prompt": "Optional: a copy of the bill. Never OTP or password.",
        "doc_prompt_hi": "वैकल्पिक: बिल की प्रति। ओटीपी या पासवर्ड कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": ["No signal or call drops", "Broadband / internet down", "Number portability stuck", "Wrong bill or overcharge", "SIM blocked or not activated"],
                "options_hi": ["नेटवर्क नहीं या कॉल ड्रॉप", "ब्रॉडबैंड / इंटरनेट बंद", "नंबर पोर्ट अटका", "गलत बिल या ओवरचार्ज", "सिम बंद या सक्रिय नहीं"],
            },
            {
                "id": "operator",
                "label": "Which telecom operator?",
                "label_hi": "कौन सी टेलीकॉम कंपनी?",
                "type": "choice",
                "options": ["Jio", "Airtel", "BSNL", "Vi (Vodafone Idea)", "Other"],
                "options_hi": ["जियो", "एयरटेल", "बीएसएनएल", "Vi (वोडाफोन आइडिया)", "अन्य"],
            },
            {
                "id": "days",
                "label": "Since when?",
                "label_hi": "कब से?",
                "type": "choice",
                "options": ["Today", "A few days", "A week", "More than a month"],
                "options_hi": ["आज", "कुछ दिन", "एक सप्ताह", "एक महीने से अधिक"],
            },
        ],
    },
    {
        "id": "railway",
        "title": "Railway service complaint",
        "title_hi": "रेलवे सेवा शिकायत",
        "blurb": "Train delay, ticket refund, dirty coach, station facility, or staff.",
        "blurb_hi": "ट्रेन लेट, टिकट रिफंड, गंदा कोच, स्टेशन सुविधा, या कर्मचारी।",
        "keywords": ["railway", "train", "ticket", "irctc", "rail", "station", "coach", "refund", "रेलवे", "ट्रेन", "टिकट"],
        "ministry": "Ministry of Railways",
        "category": "Rail services",
        "needs_photo": True,
        "photo_prompt": "Photo of the coach condition, the station issue, or a screenshot of the booking.",
        "photo_prompt_hi": "कोच की स्थिति, स्टेशन समस्या, या बुकिंग स्क्रीनशॉट की फोटो।",
        "doc_prompt": "Optional: PNR or ticket screenshot. Never OTP or full card number.",
        "doc_prompt_hi": "वैकल्पिक: PNR या टिकट स्क्रीनशॉट। ओटीपी या पूरा कार्ड नंबर कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": ["Train significantly delayed", "Ticket refund not received", "Dirty or broken coach / toilet", "Station facility missing", "Staff misbehaviour"],
                "options_hi": ["ट्रेन काफी लेट", "टिकट रिफंड नहीं मिला", "गंदा या टूटा कोच / शौचालय", "स्टेशन सुविधा गायब", "कर्मचारी का दुर्व्यवहार"],
            },
            {
                "id": "train",
                "label": "Train name or number (if relevant)",
                "label_hi": "ट्रेन का नाम या नंबर (यदि लागू हो)",
                "type": "text",
                "hint": "e.g. 12051 or Deccan Queen",
                "hint_hi": "उदा. 12051 या डेक्कन क्वीन",
            },
            {
                "id": "date",
                "label": "Date of travel / incident",
                "label_hi": "यात्रा / घटना की तारीख",
                "type": "text",
                "hint": "DD/MM/YYYY",
                "hint_hi": "दिन/माह/वर्ष",
            },
        ],
    },
    {
        "id": "health",
        "title": "Hospital or health scheme problem",
        "title_hi": "अस्पताल या स्वास्थ्य योजना समस्या",
        "blurb": "Ayushman Bharat card rejected, medicine unavailable, or doctor absent.",
        "blurb_hi": "आयुष्मान कार्ड अस्वीकार, दवा नहीं, या डॉक्टर अनुपस्थित।",
        "keywords": ["hospital", "health", "ayushman", "medical", "doctor", "medicine", "clinic", "pmjay", "स्वास्थ्य", "अस्पताल", "दवा", "डॉक्टर"],
        "ministry": "Ministry of Health & Family Welfare",
        "category": "Public health services",
        "needs_photo": False,
        "photo_prompt": "Optional: photo of closed facility or a notice on the door.",
        "photo_prompt_hi": "वैकल्पिक: बंद सुविधा या दरवाज़े पर नोटिस की फोटो।",
        "doc_prompt": "Optional: Ayushman card or prescription. Never Aadhaar or OTP.",
        "doc_prompt_hi": "वैकल्पिक: आयुष्मान कार्ड या पर्चा। आधार या ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "Ayushman / PMJAY card rejected",
                    "Medicine not available at PHC",
                    "Doctor / ANM absent",
                    "Treatment refused",
                    "Dirty / broken facility",
                ],
                "options_hi": [
                    "आयुष्मान / PMJAY कार्ड अस्वीकार",
                    "PHC पर दवा नहीं",
                    "डॉक्टर / ANM अनुपस्थित",
                    "इलाज से मना किया",
                    "गंदी / टूटी सुविधा",
                ],
            },
            {
                "id": "facility",
                "label": "Name of the hospital or health centre",
                "label_hi": "अस्पताल या स्वास्थ्य केंद्र का नाम",
                "type": "text",
                "hint": "e.g. PHC Nashik, District Hospital Pune",
                "hint_hi": "उदा. PHC नाशिक, ज़िला अस्पताल पुणे",
            },
            {
                "id": "since",
                "label": "Is this a one-time event or ongoing?",
                "label_hi": "क्या यह एक बार की घटना है या लगातार हो रहा है?",
                "type": "choice",
                "options": ["One-time incident", "Happens regularly", "Ongoing for weeks"],
                "options_hi": ["एक बार की घटना", "नियमित होता है", "हफ्तों से जारी"],
            },
        ],
    },
    {
        "id": "labour",
        "title": "Labour, MGNREGA, or ESI issue",
        "title_hi": "श्रम, मनरेगा, या ESI समस्या",
        "blurb": "MGNREGA wages unpaid, ESI denied, or labour law violation.",
        "blurb_hi": "मनरेगा मजदूरी नहीं मिली, ESI से मना, या श्रम कानून उल्लंघन।",
        "keywords": ["labour", "mgnrega", "nrega", "esi", "esic", "wages", "employment", "worker", "श्रम", "मजदूर", "मनरेगा"],
        "ministry": "Ministry of Labour and Employment",
        "category": "Labour / employment",
        "needs_photo": False,
        "photo_prompt": "Optional: job card, wage slip, or ESI card.",
        "photo_prompt_hi": "वैकल्पिक: जॉब कार्ड, मजदूरी पर्ची, या ESI कार्ड।",
        "doc_prompt": "Optional: job card or ESI card. Never Aadhaar or OTP.",
        "doc_prompt_hi": "वैकल्पिक: जॉब कार्ड या ESI कार्ड। आधार या ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "MGNREGA wages not paid",
                    "MGNREGA work not provided",
                    "ESI medical benefit denied",
                    "ESI claim or card issue",
                    "Labour law violation by employer",
                    "Provident Fund / EPFO issue",
                ],
                "options_hi": [
                    "मनरेगा मजदूरी नहीं मिली",
                    "मनरेगा काम नहीं मिला",
                    "ESI चिकित्सा लाभ से मना",
                    "ESI दावा या कार्ड समस्या",
                    "नियोक्ता द्वारा श्रम कानून उल्लंघन",
                    "प्रोविडेंट फंड / EPFO समस्या",
                ],
            },
            {
                "id": "since",
                "label": "How long has this been pending?",
                "label_hi": "यह कब से लंबित है?",
                "type": "choice",
                "options": ["Less than 1 month", "1–3 months", "3–6 months", "More than 6 months"],
                "options_hi": ["1 महीने से कम", "1–3 महीने", "3–6 महीने", "6 महीने से अधिक"],
            },
            {
                "id": "employer",
                "label": "Name of employer or contractor (if relevant)",
                "label_hi": "नियोक्ता या ठेकेदार का नाम (यदि लागू हो)",
                "type": "text",
                "hint": "Company or contractor name, or write Not applicable.",
                "hint_hi": "कंपनी या ठेकेदार का नाम, या लागू नहीं लिखें।",
            },
        ],
    },
    {
        "id": "posts",
        "title": "Post office or postal service",
        "title_hi": "पोस्ट ऑफिस या डाक सेवा",
        "blurb": "Speed post not delivered, parcel lost, or savings account issue.",
        "blurb_hi": "स्पीड पोस्ट नहीं मिला, पार्सल खोया, या बचत खाता समस्या।",
        "keywords": ["post office", "speed post", "parcel", "india post", "postage", "ippb", "डाक", "पोस्ट"],
        "ministry": "Department of Posts",
        "category": "Postal services",
        "needs_photo": False,
        "photo_prompt": "Optional: screenshot of tracking page or the receipt.",
        "photo_prompt_hi": "वैकल्पिक: ट्रैकिंग पेज या रसीद का स्क्रीनशॉट।",
        "doc_prompt": "Optional: postal receipt or tracking ID. Never OTP.",
        "doc_prompt_hi": "वैकल्पिक: डाक रसीद या ट्रैकिंग ID। ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "Speed post / registered mail not delivered",
                    "Parcel lost or damaged",
                    "Post office not functioning / closed",
                    "India Post Payments Bank (IPPB) issue",
                    "Postal Life Insurance (PLI) claim",
                    "Savings / RD account issue",
                ],
                "options_hi": [
                    "स्पीड पोस्ट / पंजीकृत डाक नहीं मिली",
                    "पार्सल खोया या क्षतिग्रस्त",
                    "पोस्ट ऑफिस काम नहीं कर रहा / बंद",
                    "India Post पेमेंट्स बैंक (IPPB) समस्या",
                    "डाक जीवन बीमा (PLI) दावा",
                    "बचत / RD खाता समस्या",
                ],
            },
            {
                "id": "tracking",
                "label": "Tracking ID or consignment number (if available)",
                "label_hi": "ट्रैकिंग ID या कंसाइनमेंट नंबर (यदि उपलब्ध हो)",
                "type": "text",
                "hint": "e.g. EW123456789IN, or write Not available.",
                "hint_hi": "उदा. EW123456789IN, या उपलब्ध नहीं लिखें।",
            },
            {
                "id": "since",
                "label": "Since when?",
                "label_hi": "कब से?",
                "type": "choice",
                "options": ["Less than a week", "1–2 weeks", "More than a month"],
                "options_hi": ["एक सप्ताह से कम", "1–2 सप्ताह", "एक महीने से अधिक"],
            },
        ],
    },
    {
        "id": "home_affairs",
        "title": "Passport, police, or home affairs",
        "title_hi": "पासपोर्ट, पुलिस, या गृह मामले",
        "blurb": "Passport delay, police inaction, FIR not filed, or citizenship issue.",
        "blurb_hi": "पासपोर्ट देरी, पुलिस निष्क्रियता, FIR दर्ज नहीं, या नागरिकता समस्या।",
        "keywords": ["passport", "police", "fir", "home affairs", "citizenship", "visa", "nrc", "पासपोर्ट", "पुलिस", "एफआईआर"],
        "ministry": "Ministry of Home Affairs",
        "category": "Home affairs",
        "needs_photo": False,
        "photo_prompt": "Optional: photo of any relevant notice or document (do not upload Aadhaar).",
        "photo_prompt_hi": "वैकल्पिक: किसी संबंधित नोटिस या दस्तावेज़ की फोटो (आधार अपलोड न करें)।",
        "doc_prompt": "Optional: acknowledgement slip or previous application. Never Aadhaar or OTP.",
        "doc_prompt_hi": "वैकल्पिक: पावती पर्ची या पिछला आवेदन। आधार या ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "kind",
                "label": "What is the problem?",
                "label_hi": "क्या समस्या है?",
                "type": "choice",
                "options": [
                    "Passport not issued or delayed",
                    "Police not taking FIR",
                    "Police inaction on complaint",
                    "Police harassment or misconduct",
                    "Citizenship / NRC document issue",
                    "Visa or OCI card issue",
                ],
                "options_hi": [
                    "पासपोर्ट जारी नहीं या देरी",
                    "पुलिस FIR नहीं ले रही",
                    "शिकायत पर पुलिस कार्रवाई नहीं",
                    "पुलिस उत्पीड़न या दुर्व्यवहार",
                    "नागरिकता / NRC दस्तावेज़ समस्या",
                    "वीज़ा या OCI कार्ड समस्या",
                ],
            },
            {
                "id": "since",
                "label": "Since when?",
                "label_hi": "कब से?",
                "type": "choice",
                "options": ["Less than 1 month", "1–3 months", "More than 3 months"],
                "options_hi": ["1 महीने से कम", "1–3 महीने", "3 महीने से अधिक"],
            },
            {
                "id": "tried",
                "label": "Have you approached the concerned office or police station already?",
                "label_hi": "क्या आप संबंधित कार्यालय या थाने में पहले जा चुके हैं?",
                "type": "choice",
                "options": ["Yes, but no result", "Not yet", "Approached multiple times"],
                "options_hi": ["हाँ, लेकिन कोई नतीजा नहीं", "अभी नहीं", "कई बार जा चुके हैं"],
            },
        ],
    },
    {
        "id": "general",
        "title": "Other / describe your problem",
        "title_hi": "अन्य / अपनी समस्या बताएँ",
        "blurb": "Type your problem and AI will find the right department.",
        "blurb_hi": "अपनी समस्या लिखें, AI सही विभाग ढूँढेगा।",
        "keywords": [],
        "ministry": "Department of Administrative Reforms & Public Grievances",
        "category": "General public grievance",
        "needs_photo": False,
        "photo_prompt": "A photo helps if the problem can be seen. Skip if it is only paperwork.",
        "photo_prompt_hi": "यदि समस्या दिखती है तो फोटो मदद करती है। केवल कागज़ हो तो छोड़ दें।",
        "doc_prompt": "Optional: a previous reply or a bill. Never Aadhaar, PAN, or OTP.",
        "doc_prompt_hi": "वैकल्पिक: पिछला जवाब या बिल। आधार, पैन या ओटीपी कभी नहीं।",
        "questions": [
            {
                "id": "story",
                "label": "Tell the problem in plain words",
                "label_hi": "समस्या सादे शब्दों में बताएँ",
                "type": "text",
                "hint": "What happened, when, and what you want done.",
                "hint_hi": "क्या हुआ, कब, और आप क्या चाहते हैं।",
            }
        ],
    },
]


def list_playbooks() -> list[dict]:
    return PLAYBOOKS


def get_playbook(playbook_id: str | None) -> dict:
    wanted = (playbook_id or "").strip()
    for item in PLAYBOOKS:
        if item["id"] == wanted:
            return item
    return PLAYBOOKS[-1]


def detect_playbook(text: str) -> dict:
    lowered = (text or "").lower()
    best: tuple[int, dict] | None = None
    for item in PLAYBOOKS:
        if item["id"] == "general":
            continue
        hits = sum(1 for word in item["keywords"] if word in lowered)
        if hits and (best is None or hits > best[0]):
            best = (hits, item)
    return best[1] if best else PLAYBOOKS[-1]


def assemble_description(
    playbook: dict,
    answers: dict,
    location: dict,
    helper: dict | None = None,
) -> str:
    lines = [playbook["title"] + "."]
    labels = {q["id"]: q["label"] for q in playbook.get("questions", [])}
    for key, value in (answers or {}).items():
        if not value:
            continue
        lines.append(f"{labels.get(key, key)}: {value}")
    place = ", ".join(
        part
        for part in [
            location.get("street"),
            location.get("village"),
            location.get("ward") and f"Ward {location['ward']}",
            location.get("district"),
        ]
        if part
    )
    if place:
        lines.append(f"Place: {place}.")
    if location.get("latitude") and location.get("longitude"):
        lines.append(f"Pin: {location['latitude']}, {location['longitude']}.")
    if helper and helper.get("role") == "helper":
        lines.append(
            f"Filed with help from {helper.get('helper_name') or 'a helper'}"
            f" ({helper.get('helper_relation') or 'CSC / family'}) for the citizen named above."
        )
    return "\n".join(lines)
